### ISSUE TITLE
Question About the API

### ISSUE THREAD

**Issue by Jouzep** [dreamingspires/auction-scraper#9]
Hello how did you find the endpoint are the parameters of each endpoints? 
Is there a documentation

**Comment by eddsalkield** [comment]
Unfortunately there is no documentation for the endpoints; the data is obtained by scraping.
By inspecting the code you can see how the data is extracted, for example [here](https://github.com/dreamingspires/auction-scraper/blob/a6d0dabcd8f17e937758da9e0ce451dfca3828c0/auction_scraper/scrapers/ebay/scraper.py#L352).
